[package]
authors = ["Alexander Nikolaev <alexander.nikolaev@unikie.com>"]
edition = "2021"
license = "Apache 2.0"
name = "givc"
publish = false
version = "0.0.1"

[dependencies]
anyhow = "1.0.86"
async-channel = "2.3.1"
async-stream = "0.3"
clap = { version = "4.5.4", features = ["derive", "env"] }
console = "0.15"
prost = "0.13"
regex = "1.11"
surf = { version = "2.3.2", default-features = false, features = [
  "h1-client-rustls",
] }
serde_json = "1.0.120"
serde = { version = "1.0.202", features = ["derive"] }
strum = { version = "0.26", features = ["derive"] }
tokio-stream = "0.1"
tokio = { version = "1.0", features = [
  "rt-multi-thread",
  "time",
  "macros",
  "fs",
] }
tokio-vsock = "0.5"
tonic-reflection = "0.12"
tonic-types = "0.12"
tonic = { version = "0.12", features = ["tls"] }
tower = "0.4"
tracing = "0.1"
tracing-journald = "0.2.0"
tracing-subscriber = { version = "0.3", features = [
  "env-filter",
  "tracing-log",
  "time",
  "local-time",
] }
x509-parser = "0.16"

# GIVC subparts
givc-common = { path = "../common" }
givc-client = { path = "../client" }

[dependencies.tokio-listener]
features = ["multi-listener", "tonic012", "vsock"]
git = "https://github.com/avnik/tokio-listener"
branch = "avnik/vsock-ghaf"
