// SPDX-FileCopyrightText: 2024-2026 TII (SSRC) and the Ghaf contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: exec/exec.proto

package exec

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Exec_GetUptime_FullMethodName    = "/exec.Exec/GetUptime"
	Exec_RunOtaUpdate_FullMethodName = "/exec.Exec/RunOtaUpdate"
)

// ExecClient is the client API for Exec service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Dedicated, strongly typed service replacing generic shell/command execution
type ExecClient interface {
	// Dedicated RPC for retrieving system uptime without process spawning
	GetUptime(ctx context.Context, in *UptimeRequest, opts ...grpc.CallOption) (*UptimeResponse, error)
	// Dedicated RPC for executing typed OTA updates
	RunOtaUpdate(ctx context.Context, in *OtaUpdateRequest, opts ...grpc.CallOption) (*OtaUpdateResponse, error)
}

type execClient struct {
	cc grpc.ClientConnInterface
}

func NewExecClient(cc grpc.ClientConnInterface) ExecClient {
	return &execClient{cc}
}

func (c *execClient) GetUptime(ctx context.Context, in *UptimeRequest, opts ...grpc.CallOption) (*UptimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UptimeResponse)
	err := c.cc.Invoke(ctx, Exec_GetUptime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *execClient) RunOtaUpdate(ctx context.Context, in *OtaUpdateRequest, opts ...grpc.CallOption) (*OtaUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OtaUpdateResponse)
	err := c.cc.Invoke(ctx, Exec_RunOtaUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExecServer is the server API for Exec service.
// All implementations must embed UnimplementedExecServer
// for forward compatibility.
//
// Dedicated, strongly typed service replacing generic shell/command execution
type ExecServer interface {
	// Dedicated RPC for retrieving system uptime without process spawning
	GetUptime(context.Context, *UptimeRequest) (*UptimeResponse, error)
	// Dedicated RPC for executing typed OTA updates
	RunOtaUpdate(context.Context, *OtaUpdateRequest) (*OtaUpdateResponse, error)
	mustEmbedUnimplementedExecServer()
}

// UnimplementedExecServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExecServer struct{}

func (UnimplementedExecServer) GetUptime(context.Context, *UptimeRequest) (*UptimeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUptime not implemented")
}
func (UnimplementedExecServer) RunOtaUpdate(context.Context, *OtaUpdateRequest) (*OtaUpdateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunOtaUpdate not implemented")
}
func (UnimplementedExecServer) mustEmbedUnimplementedExecServer() {}
func (UnimplementedExecServer) testEmbeddedByValue()              {}

// UnsafeExecServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExecServer will
// result in compilation errors.
type UnsafeExecServer interface {
	mustEmbedUnimplementedExecServer()
}

func RegisterExecServer(s grpc.ServiceRegistrar, srv ExecServer) {
	// If the following call panics, it indicates UnimplementedExecServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Exec_ServiceDesc, srv)
}

func _Exec_GetUptime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UptimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecServer).GetUptime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exec_GetUptime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecServer).GetUptime(ctx, req.(*UptimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exec_RunOtaUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OtaUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecServer).RunOtaUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exec_RunOtaUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecServer).RunOtaUpdate(ctx, req.(*OtaUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Exec_ServiceDesc is the grpc.ServiceDesc for Exec service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Exec_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "exec.Exec",
	HandlerType: (*ExecServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUptime",
			Handler:    _Exec_GetUptime_Handler,
		},
		{
			MethodName: "RunOtaUpdate",
			Handler:    _Exec_RunOtaUpdate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "exec/exec.proto",
}
