// SPDX-FileCopyrightText: 2024-2026 TII (SSRC) and the Ghaf contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: exec/exec.proto

package exec

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Allowed OTA action types
type OtaAction int32

const (
	OtaAction_OTA_ACTION_UNSPECIFIED OtaAction = 0
	OtaAction_OTA_ACTION_GET         OtaAction = 1
	OtaAction_OTA_ACTION_CACHIX      OtaAction = 2
)

// Enum value maps for OtaAction.
var (
	OtaAction_name = map[int32]string{
		0: "OTA_ACTION_UNSPECIFIED",
		1: "OTA_ACTION_GET",
		2: "OTA_ACTION_CACHIX",
	}
	OtaAction_value = map[string]int32{
		"OTA_ACTION_UNSPECIFIED": 0,
		"OTA_ACTION_GET":         1,
		"OTA_ACTION_CACHIX":      2,
	}
)

func (x OtaAction) Enum() *OtaAction {
	p := new(OtaAction)
	*p = x
	return p
}

func (x OtaAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OtaAction) Descriptor() protoreflect.EnumDescriptor {
	return file_exec_exec_proto_enumTypes[0].Descriptor()
}

func (OtaAction) Type() protoreflect.EnumType {
	return &file_exec_exec_proto_enumTypes[0]
}

func (x OtaAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OtaAction.Descriptor instead.
func (OtaAction) EnumDescriptor() ([]byte, []int) {
	return file_exec_exec_proto_rawDescGZIP(), []int{0}
}

// Request to query system uptime
type UptimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UptimeRequest) Reset() {
	*x = UptimeRequest{}
	mi := &file_exec_exec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UptimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UptimeRequest) ProtoMessage() {}

func (x *UptimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exec_exec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UptimeRequest.ProtoReflect.Descriptor instead.
func (*UptimeRequest) Descriptor() ([]byte, []int) {
	return file_exec_exec_proto_rawDescGZIP(), []int{0}
}

// Structured response for system uptime
type UptimeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UptimeSeconds float64                `protobuf:"fixed64,1,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	IdleSeconds   float64                `protobuf:"fixed64,2,opt,name=idle_seconds,json=idleSeconds,proto3" json:"idle_seconds,omitempty"`
	Formatted     string                 `protobuf:"bytes,3,opt,name=formatted,proto3" json:"formatted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UptimeResponse) Reset() {
	*x = UptimeResponse{}
	mi := &file_exec_exec_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UptimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UptimeResponse) ProtoMessage() {}

func (x *UptimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exec_exec_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UptimeResponse.ProtoReflect.Descriptor instead.
func (*UptimeResponse) Descriptor() ([]byte, []int) {
	return file_exec_exec_proto_rawDescGZIP(), []int{1}
}

func (x *UptimeResponse) GetUptimeSeconds() float64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *UptimeResponse) GetIdleSeconds() float64 {
	if x != nil {
		return x.IdleSeconds
	}
	return 0
}

func (x *UptimeResponse) GetFormatted() string {
	if x != nil {
		return x.Formatted
	}
	return ""
}

// Request to execute a dedicated OTA update operation
type OtaUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        OtaAction              `protobuf:"varint,1,opt,name=action,proto3,enum=exec.OtaAction" json:"action,omitempty"`
	Pin           *string                `protobuf:"bytes,2,opt,name=pin,proto3,oneof" json:"pin,omitempty"`
	Cache         *string                `protobuf:"bytes,3,opt,name=cache,proto3,oneof" json:"cache,omitempty"`
	Token         *string                `protobuf:"bytes,4,opt,name=token,proto3,oneof" json:"token,omitempty"`
	CachixHost    *string                `protobuf:"bytes,5,opt,name=cachix_host,json=cachixHost,proto3,oneof" json:"cachix_host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OtaUpdateRequest) Reset() {
	*x = OtaUpdateRequest{}
	mi := &file_exec_exec_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OtaUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OtaUpdateRequest) ProtoMessage() {}

func (x *OtaUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exec_exec_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OtaUpdateRequest.ProtoReflect.Descriptor instead.
func (*OtaUpdateRequest) Descriptor() ([]byte, []int) {
	return file_exec_exec_proto_rawDescGZIP(), []int{2}
}

func (x *OtaUpdateRequest) GetAction() OtaAction {
	if x != nil {
		return x.Action
	}
	return OtaAction_OTA_ACTION_UNSPECIFIED
}

func (x *OtaUpdateRequest) GetPin() string {
	if x != nil && x.Pin != nil {
		return *x.Pin
	}
	return ""
}

func (x *OtaUpdateRequest) GetCache() string {
	if x != nil && x.Cache != nil {
		return *x.Cache
	}
	return ""
}

func (x *OtaUpdateRequest) GetToken() string {
	if x != nil && x.Token != nil {
		return *x.Token
	}
	return ""
}

func (x *OtaUpdateRequest) GetCachixHost() string {
	if x != nil && x.CachixHost != nil {
		return *x.CachixHost
	}
	return ""
}

// Response for an OTA update operation
type OtaUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReturnCode    int32                  `protobuf:"varint,1,opt,name=return_code,json=returnCode,proto3" json:"return_code,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OtaUpdateResponse) Reset() {
	*x = OtaUpdateResponse{}
	mi := &file_exec_exec_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OtaUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OtaUpdateResponse) ProtoMessage() {}

func (x *OtaUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exec_exec_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OtaUpdateResponse.ProtoReflect.Descriptor instead.
func (*OtaUpdateResponse) Descriptor() ([]byte, []int) {
	return file_exec_exec_proto_rawDescGZIP(), []int{3}
}

func (x *OtaUpdateResponse) GetReturnCode() int32 {
	if x != nil {
		return x.ReturnCode
	}
	return 0
}

func (x *OtaUpdateResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *OtaUpdateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_exec_exec_proto protoreflect.FileDescriptor

const file_exec_exec_proto_rawDesc = "" +
	"\n" +
	"\x0fexec/exec.proto\x12\x04exec\"\x0f\n" +
	"\rUptimeRequest\"x\n" +
	"\x0eUptimeResponse\x12%\n" +
	"\x0euptime_seconds\x18\x01 \x01(\x01R\ruptimeSeconds\x12!\n" +
	"\fidle_seconds\x18\x02 \x01(\x01R\vidleSeconds\x12\x1c\n" +
	"\tformatted\x18\x03 \x01(\tR\tformatted\"\xda\x01\n" +
	"\x10OtaUpdateRequest\x12'\n" +
	"\x06action\x18\x01 \x01(\x0e2\x0f.exec.OtaActionR\x06action\x12\x15\n" +
	"\x03pin\x18\x02 \x01(\tH\x00R\x03pin\x88\x01\x01\x12\x19\n" +
	"\x05cache\x18\x03 \x01(\tH\x01R\x05cache\x88\x01\x01\x12\x19\n" +
	"\x05token\x18\x04 \x01(\tH\x02R\x05token\x88\x01\x01\x12$\n" +
	"\vcachix_host\x18\x05 \x01(\tH\x03R\n" +
	"cachixHost\x88\x01\x01B\x06\n" +
	"\x04_pinB\b\n" +
	"\x06_cacheB\b\n" +
	"\x06_tokenB\x0e\n" +
	"\f_cachix_host\"b\n" +
	"\x11OtaUpdateResponse\x12\x1f\n" +
	"\vreturn_code\x18\x01 \x01(\x05R\n" +
	"returnCode\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error*R\n" +
	"\tOtaAction\x12\x1a\n" +
	"\x16OTA_ACTION_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eOTA_ACTION_GET\x10\x01\x12\x15\n" +
	"\x11OTA_ACTION_CACHIX\x10\x022\x7f\n" +
	"\x04Exec\x126\n" +
	"\tGetUptime\x12\x13.exec.UptimeRequest\x1a\x14.exec.UptimeResponse\x12?\n" +
	"\fRunOtaUpdate\x12\x16.exec.OtaUpdateRequest\x1a\x17.exec.OtaUpdateResponseB\x17Z\x15givc/modules/api/execb\x06proto3"

var (
	file_exec_exec_proto_rawDescOnce sync.Once
	file_exec_exec_proto_rawDescData []byte
)

func file_exec_exec_proto_rawDescGZIP() []byte {
	file_exec_exec_proto_rawDescOnce.Do(func() {
		file_exec_exec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_exec_exec_proto_rawDesc), len(file_exec_exec_proto_rawDesc)))
	})
	return file_exec_exec_proto_rawDescData
}

var file_exec_exec_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_exec_exec_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_exec_exec_proto_goTypes = []any{
	(OtaAction)(0),            // 0: exec.OtaAction
	(*UptimeRequest)(nil),     // 1: exec.UptimeRequest
	(*UptimeResponse)(nil),    // 2: exec.UptimeResponse
	(*OtaUpdateRequest)(nil),  // 3: exec.OtaUpdateRequest
	(*OtaUpdateResponse)(nil), // 4: exec.OtaUpdateResponse
}
var file_exec_exec_proto_depIdxs = []int32{
	0, // 0: exec.OtaUpdateRequest.action:type_name -> exec.OtaAction
	1, // 1: exec.Exec.GetUptime:input_type -> exec.UptimeRequest
	3, // 2: exec.Exec.RunOtaUpdate:input_type -> exec.OtaUpdateRequest
	2, // 3: exec.Exec.GetUptime:output_type -> exec.UptimeResponse
	4, // 4: exec.Exec.RunOtaUpdate:output_type -> exec.OtaUpdateResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_exec_exec_proto_init() }
func file_exec_exec_proto_init() {
	if File_exec_exec_proto != nil {
		return
	}
	file_exec_exec_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_exec_exec_proto_rawDesc), len(file_exec_exec_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_exec_exec_proto_goTypes,
		DependencyIndexes: file_exec_exec_proto_depIdxs,
		EnumInfos:         file_exec_exec_proto_enumTypes,
		MessageInfos:      file_exec_exec_proto_msgTypes,
	}.Build()
	File_exec_exec_proto = out.File
	file_exec_exec_proto_goTypes = nil
	file_exec_exec_proto_depIdxs = nil
}
