// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: policyagent/policyagent.proto

package policyagent

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PolicyAgent_StreamPolicy_FullMethodName = "/policyagent.PolicyAgent/StreamPolicy"
)

// PolicyAgentClient is the client API for PolicyAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PolicyAgentClient interface {
	StreamPolicy(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PolicyUpdate, PolicyUpdate], error)
}

type policyAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewPolicyAgentClient(cc grpc.ClientConnInterface) PolicyAgentClient {
	return &policyAgentClient{cc}
}

func (c *policyAgentClient) StreamPolicy(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PolicyUpdate, PolicyUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PolicyAgent_ServiceDesc.Streams[0], PolicyAgent_StreamPolicy_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PolicyUpdate, PolicyUpdate]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PolicyAgent_StreamPolicyClient = grpc.BidiStreamingClient[PolicyUpdate, PolicyUpdate]

// PolicyAgentServer is the server API for PolicyAgent service.
// All implementations must embed UnimplementedPolicyAgentServer
// for forward compatibility.
type PolicyAgentServer interface {
	StreamPolicy(grpc.BidiStreamingServer[PolicyUpdate, PolicyUpdate]) error
	mustEmbedUnimplementedPolicyAgentServer()
}

// UnimplementedPolicyAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPolicyAgentServer struct{}

func (UnimplementedPolicyAgentServer) StreamPolicy(grpc.BidiStreamingServer[PolicyUpdate, PolicyUpdate]) error {
	return status.Errorf(codes.Unimplemented, "method StreamPolicy not implemented")
}
func (UnimplementedPolicyAgentServer) mustEmbedUnimplementedPolicyAgentServer() {}
func (UnimplementedPolicyAgentServer) testEmbeddedByValue()                     {}

// UnsafePolicyAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PolicyAgentServer will
// result in compilation errors.
type UnsafePolicyAgentServer interface {
	mustEmbedUnimplementedPolicyAgentServer()
}

func RegisterPolicyAgentServer(s grpc.ServiceRegistrar, srv PolicyAgentServer) {
	// If the following call pancis, it indicates UnimplementedPolicyAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PolicyAgent_ServiceDesc, srv)
}

func _PolicyAgent_StreamPolicy_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PolicyAgentServer).StreamPolicy(&grpc.GenericServerStream[PolicyUpdate, PolicyUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PolicyAgent_StreamPolicyServer = grpc.BidiStreamingServer[PolicyUpdate, PolicyUpdate]

// PolicyAgent_ServiceDesc is the grpc.ServiceDesc for PolicyAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PolicyAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "policyagent.PolicyAgent",
	HandlerType: (*PolicyAgentServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamPolicy",
			Handler:       _PolicyAgent_StreamPolicy_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "policyagent/policyagent.proto",
}
