// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: policyagent/policyagent.proto

package policyagent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamPolicyRequest) Reset() {
	*x = StreamPolicyRequest{}
	mi := &file_policyagent_policyagent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamPolicyRequest) ProtoMessage() {}

func (x *StreamPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_policyagent_policyagent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamPolicyRequest.ProtoReflect.Descriptor instead.
func (*StreamPolicyRequest) Descriptor() ([]byte, []int) {
	return file_policyagent_policyagent_proto_rawDescGZIP(), []int{0}
}

func (x *StreamPolicyRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type PolicyUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyUpdate) Reset() {
	*x = PolicyUpdate{}
	mi := &file_policyagent_policyagent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyUpdate) ProtoMessage() {}

func (x *PolicyUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_policyagent_policyagent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyUpdate.ProtoReflect.Descriptor instead.
func (*PolicyUpdate) Descriptor() ([]byte, []int) {
	return file_policyagent_policyagent_proto_rawDescGZIP(), []int{1}
}

func (x *PolicyUpdate) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_policyagent_policyagent_proto protoreflect.FileDescriptor

const file_policyagent_policyagent_proto_rawDesc = "" +
	"\n" +
	"\x1dpolicyagent/policyagent.proto\x12\vpolicyagent\"4\n" +
	"\x13StreamPolicyRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"(\n" +
	"\fPolicyUpdate\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2W\n" +
	"\vPolicyAgent\x12H\n" +
	"\fStreamPolicy\x12\x19.policyagent.PolicyUpdate\x1a\x19.policyagent.PolicyUpdate(\x010\x01B\x1eZ\x1cgivc/modules/api/policyagentb\x06proto3"

var (
	file_policyagent_policyagent_proto_rawDescOnce sync.Once
	file_policyagent_policyagent_proto_rawDescData []byte
)

func file_policyagent_policyagent_proto_rawDescGZIP() []byte {
	file_policyagent_policyagent_proto_rawDescOnce.Do(func() {
		file_policyagent_policyagent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_policyagent_policyagent_proto_rawDesc), len(file_policyagent_policyagent_proto_rawDesc)))
	})
	return file_policyagent_policyagent_proto_rawDescData
}

var file_policyagent_policyagent_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_policyagent_policyagent_proto_goTypes = []any{
	(*StreamPolicyRequest)(nil), // 0: policyagent.StreamPolicyRequest
	(*PolicyUpdate)(nil),        // 1: policyagent.PolicyUpdate
}
var file_policyagent_policyagent_proto_depIdxs = []int32{
	1, // 0: policyagent.PolicyAgent.StreamPolicy:input_type -> policyagent.PolicyUpdate
	1, // 1: policyagent.PolicyAgent.StreamPolicy:output_type -> policyagent.PolicyUpdate
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_policyagent_policyagent_proto_init() }
func file_policyagent_policyagent_proto_init() {
	if File_policyagent_policyagent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_policyagent_policyagent_proto_rawDesc), len(file_policyagent_policyagent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_policyagent_policyagent_proto_goTypes,
		DependencyIndexes: file_policyagent_policyagent_proto_depIdxs,
		MessageInfos:      file_policyagent_policyagent_proto_msgTypes,
	}.Build()
	File_policyagent_policyagent_proto = out.File
	file_policyagent_policyagent_proto_goTypes = nil
	file_policyagent_policyagent_proto_depIdxs = nil
}
